#! /usr/bin/env sh

# File to test
EXP_SCRIPT="scrabble"

# Text colors
Red='\033[0;31m'
Color_Off='\033[0m' 
Green='\033[0;32m'

# Test counters
NB_TEST_OK=0
NB_TEST_TOTAL=0

##################################################
# check command line params
##################################################
GIVEN_SCRIPT=""
if [ $# -eq 1 ]
then
    GIVEN_SCRIPT="${1}"
else
    echo "Only the script name is allowed in command line"
fi

##################################################
# Check if python is available
##################################################
pyapp=`which python`
if [ "${pyapp:0:1}" == "/" ]
then
    python --version
else
    echo "Python not found"
    exit
fi

##################################################
# Check if the script has been given
##################################################
if [ "${GIVEN_SCRIPT}" != "${EXP_SCRIPT}" ]
then
    echo "You must give ${EXP_SCRIPT} in param"
    exit
fi

##################################################
# Check if the given script exists
##################################################
if [ ! -f "${EXP_SCRIPT}" ]
then
    echo "File not found: ${EXP_SCRIPT}"
    exit
fi

##################################################
# Test function
##################################################
run_test () {
    TEST_NAME=$1
    TEST_NUM=$2
    TEST_IN=.test/${TEST_NUM}.in
    TEST_EXP=.test/${TEST_NUM}.exp
    TEST_OUT=".test/${TEST_NUM}_test.out"
    TEST_DIFF=".test/${TEST_NUM}_test.diff"
    ./${EXP_SCRIPT} < ${TEST_IN}  > ${TEST_OUT}
    diff ${TEST_EXP} ${TEST_OUT} > ${TEST_DIFF}
    NB_DIFF=`cat ${TEST_DIFF} | wc -l`
    NB_TEST_TOTAL=$((NB_TEST_TOTAL+1))
    if [ ${NB_DIFF} -eq 0 ]
    then
        echo "- ${TEST_NUM} ${Green}\xE2\x9C\x94${Color_Off} ${TEST_NAME}"
        rm ${TEST_OUT}
        rm ${TEST_DIFF}
        NB_TEST_OK=$((NB_TEST_OK+1))
    else
        echo ""
        echo "- ${TEST_NUM} ${Red}\xE2\x9C\x97${Color_Off} ${TEST_NAME}"
        echo "${Green}Expected${Color_Off}"
        grep "<" ${TEST_DIFF}
        echo "${Red}Given${Color_Off}"
        grep ">" ${TEST_DIFF}
        echo ""
    fi
}

##################################################
# Run tests
##################################################
run_test "Scrabble Question? Question!" "01"
run_test "Scrabble red wheelbarrow" "02"
run_test "Scrabble COMPUTER science" "03"
run_test "Scrabble Scrabble wiNNeR" "04"
run_test "Scrabble   " "05"

##################################################
# Print Summary
##################################################
if [ ${NB_TEST_OK} -eq ${NB_TEST_TOTAL} ]
then
    echo "Validated: ${Green}${NB_TEST_OK}/${NB_TEST_TOTAL}${Color_Off}"
else
    echo "Validated: ${Red}${NB_TEST_OK}/${NB_TEST_TOTAL}${Color_Off}"
fi
